run_name: sample-cnn-all
batch_size: 8
epochs: 100
learning_rate: 0.005
patience: 10

model:
  architecture: cnn
  channels:
    - all
  embedding_dim: 256
  base_channels: 32
  dropout: 0.2

data:
  version: 2
  data_folder: dataset
  generate: false
  window_size: 20
  step: 1
  verbose: true

split:
  strategy: session
  shuffle: false
  train_sessions:
    - session_STBPRO1@824C26_20260210_122839
    - session_STBPRO1@824C26_20260210_141443
    - session_STBPRO1@824C26_20260210_151550
    - session_STBPRO3@71E957_20260210_122725
    - session_STBPRO3@71E957_20260210_141443
    - session_STBPRO3@71E957_20260210_151552
  val_sessions:
    - session_STBPRO1@824C26_20260211_094115
  test_sessions:
    - session_STBPRO3@71E957_20260211_094114

wandb:
  enabled: true
  project: pothole-detection
  entity: potholes-team
  mode: online
  tags:
    - baseline
    - ast
    - session-split
  log_split_artifact: true
  log_training_artifact: true
  log_model_artifact: true
  log_dataset_artifact: false
  log_batch_metrics: true
  log_batch_interval: 25
